name: docs_pages_workflow 

on: 
  push:
    branches: [ main ]   

jobs:

  build_docs_job:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Set up Python
      uses: actions/setup-python@v2.2.1
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install -U sphinx
        python -m pip install sphinx-rtd-theme
    
    - name: make the sphinx docs
      run: |
        sphinx-build -M clean . _build
        sphinx-build -M html  . _build
              
    - name: Add .nojekyll file
      run: touch ./_build/html/.nojekyll

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages
        folder: _build/html
      
